version: "3.7"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        DD_API_KEY: ${DD_API_KEY}
    container_name: sample-api
    ports:
      - 8080:8080
    environment:
      - DD_ENV=dev
      - DD_HOSTNAME=local
  # app:
    # build: 
      # context: ./app
      # dockerfile: Dockerfile
    # image: sample-app
    # container_name: sample-app
    # ports:
      # - 3000:3000
    # environment:
      # MYSQL_HOST: mysql
      # MYSQL_USER: root
      # MYSQL_PASSWORD: secret
      # MYSQL_DB: todos
      # DD_SERVICE: todo
      # DD_AGENT_HOST: datadog

  # mysql:
    # image: mysql:5.7
    # container_name: sample-mysql
    # volumes:
      # - todo-mysql-data:/var/lib/mysql
    # environment: 
      # MYSQL_ROOT_PASSWORD: secret
      # MYSQL_DATABASE: todos
    
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: sample-nginx
    image: sample-nginx
    labels:
      com.datadoghq.tags.env: 'dev'
      com.datadoghq.tags.service: 'sample-nginx'
      com.datadoghq.tags.version: '0.1.0'
      com.datadoghq.ad.check_names: '["nginx"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: '[{"nginx_status_url": "http://%%host%%:81/nginx_status/"}]'
      com.datadoghq.ad.logs: '[{"source": "nginx", "service": "sample-nginx"}]'
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
    ports:
      - "8888:80"
    environment:
      DD_AGENT_HOST: datadog
      DD_TRACE_AGENT_PORT: 8126

  datadog: 
    image: datadog/agent:7
    container_name: sample-ddagent
    environment:
      - DD_API_KEY
      - DD_SITE=datadoghq.com
      - DD_ENV=dev
      - DD_HOSTNAME=local
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLET_ALL=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    ports:
      - "8126:8126/tcp"

# volumes:
  # todo-mysql-data:
